import * as cdk from 'aws-cdk-lib';
import type * as codecommit from 'aws-cdk-lib/aws-codecommit';
import type * as s3 from 'aws-cdk-lib/aws-s3';
import { NagSuppressions } from 'cdk-nag';
import type { Construct } from 'constructs';
import { ApplicationStage } from '../application/application-stage.js';
import { ArtifactsBucket } from './artifacts/artifacts-bucket.js';
import { DeliveryPipeline } from './delivery-pipeline/delivery-pipeline.js';

interface DeliveryPipelineStackProps extends cdk.StackProps {
  readonly repository: codecommit.IRepository;
  readonly serverAccessLogsBucket: s3.IBucket;
}

export class DeliveryPipelineStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props: DeliveryPipelineStackProps) {
    super(scope, id, {
      description: 'Provisions the pipeline for CDK delivery patterns',
      ...props,
    });

    const { env, repository, serverAccessLogsBucket } = props;

    const { bucket: artifactBucket } = new ArtifactsBucket(
      this,
      'ArtifactsBucket',
      {
        serverAccessLogsBucket,
      }
    );
    const stage = new ApplicationStage(this, 'Dev', {
      env,
    });

    new DeliveryPipeline(this, 'Pipeline', {
      artifactBucket,
      repository,
      stage,
    });

    NagSuppressions.addStackSuppressions(this, [
      {
        id: 'AwsSolutions-CB4',
        reason:
          'CodeBuild projects are created by CDK Pipelines internally and do not expose an encryptionKey option via CodeBuildOptions.',
      },
      {
        id: 'AwsSolutions-IAM5',
        reason:
          'Wildcard permissions are generated by CDK Pipelines internal constructs and cannot be further constrained.',
      },
    ]);
  }
}
