import * as cdk from 'aws-cdk-lib';
import * as codebuild from 'aws-cdk-lib/aws-codebuild';
import type * as codecommit from 'aws-cdk-lib/aws-codecommit';
import * as kms from 'aws-cdk-lib/aws-kms';
import * as s3 from 'aws-cdk-lib/aws-s3';
import {
  CodePipeline,
  CodePipelineSource,
  ShellStep,
} from 'aws-cdk-lib/pipelines';
import { NagSuppressions } from 'cdk-nag';
import type { Construct } from 'constructs';
import { ApplicationStage } from '../application/application-stage.js';

interface DeliveryPipelineStackProps extends cdk.StackProps {
  readonly repository: codecommit.IRepository;
}

export class DeliveryPipelineStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props: DeliveryPipelineStackProps) {
    super(scope, id, {
      description: 'Provisions the pipeline for CDK delivery patterns',
      ...props,
    });

    const key = new kms.Key(this, 'PipelineKey', {
      alias: 'alias/aws-cdk-delivery-patterns/pipeline-artifacts',
      enableKeyRotation: true,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    const accessLogsBucket = new s3.Bucket(this, 'ArtifactsAccessLogsBucket', {
      autoDeleteObjects: true,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      encryption: s3.BucketEncryption.S3_MANAGED,
      enforceSSL: true,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    const artifactBucket = new s3.Bucket(this, 'ArtifactsBucket', {
      autoDeleteObjects: true,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      encryption: s3.BucketEncryption.KMS,
      encryptionKey: key,
      enforceSSL: true,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      serverAccessLogsBucket: accessLogsBucket,
    });

    const pipeline = new CodePipeline(this, 'Pipeline', {
      artifactBucket,
      pipelineName: 'AwsCdkDeliveryPatternsPipeline',
      selfMutation: true,
      selfMutationCodeBuildDefaults: {
        buildEnvironment: {
          buildImage: codebuild.LinuxBuildImage.STANDARD_7_0,
        },
        partialBuildSpec: codebuild.BuildSpec.fromObject({
          version: 0.2,
          phases: {
            install: {
              'runtime-versions': {
                nodejs: 24,
              },
              commands: ['npm install -g npm@11.10.1'],
            },
          },
        }),
      },
      synth: new ShellStep('Synth', {
        input: CodePipelineSource.codeCommit(props.repository, 'main'),
        commands: ['npm ci', 'npm run build', 'npx cdk synth'],
      }),
      synthCodeBuildDefaults: {
        buildEnvironment: {
          buildImage: codebuild.LinuxBuildImage.STANDARD_7_0,
        },
        partialBuildSpec: codebuild.BuildSpec.fromObject({
          version: 0.2,
          phases: {
            install: {
              'runtime-versions': {
                nodejs: 24,
              },
              commands: ['npm install -g npm@11.10.1'],
            },
          },
        }),
      },
    });

    const stage = new ApplicationStage(this, 'Dev', {
      env: props.env,
    });

    pipeline.addStage(stage);

    NagSuppressions.addStackSuppressions(this, [
      {
        id: 'AwsSolutions-CB4',
        reason:
          'CodeBuild projects are created by CDK Pipelines internally and do not expose an encryptionKey option via CodeBuildOptions.',
      },
      {
        id: 'AwsSolutions-IAM5',
        reason:
          'Wildcard permissions are generated by CDK Pipelines internal constructs and cannot be further constrained.',
      },
    ]);
  }
}
